version: "2"

services:
  api:
    volumes:
      - ".:/usr/src/app"
    command: watchmedo auto-restart -d /usr/src/app -p "*.py" -D -R -- gunicorn -k gevent -b 0.0.0.0:5001 reprof_rest.application:app
    environment:
      - REPROF_REST_SETTINGS=/usr/src/app/dev_settings.py
