version: "2"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn -k gevent -b 0.0.0.0:5001 reprof_rest.application:app --timeout 3600 --limit-request-line 16376
    environment:
      - REPROF_REST_SETTINGS=/usr/src/app/prd_settings.py
    ports:
      - "5001:5001"
